### ISSUE TITLE
Evaluate templates in growthbook/templates/ingress.yaml

### ISSUE THREAD

**Issue by ZoltanOnody** [one-acre-fund/oaf-public-charts#153]
Hi! 

I have a use case where I need to setup multiple GrowthBook instances. 

In `values.yaml` I want to configure GrowthBook ingress as:

```
ingress:
  enabled: true
  ...
  annotations:
    ...
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://growthbook-{{ .Values.ciEnvironmentSlug }}.example.io"
  appOriginName: growthbook-{{ .Values.ciEnvironmentSlug }}.example.io
  apiHostName: growthbook-api-{{ .Values.ciEnvironmentSlug }}.example.io
```

And provide the `ciEnvironmentSlug` via `--set`. Otherwise, I would have to provide all the URLs via `--set` and the command would get messy.

To "fix" it, I pulled the chart and modified `growthbook/templates/ingress.yaml` as:

```diff
diff --git a/misc/deploy/helm/growthbook/charts/growthbook/templates/ingress.yaml b/misc/deploy/helm/growthbook/charts/growthbook/templates/ingress.yaml
index 13099c727..1c2360d8b 100644
--- a/misc/deploy/helm/growthbook/charts/growthbook/templates/ingress.yaml
+++ b/misc/deploy/helm/growthbook/charts/growthbook/templates/ingress.yaml
@@ -4,10 +4,10 @@ kind: Ingress
 metadata:
   name: {{ .Values.ingress.name }}
   annotations:
-    {{- toYaml .Values.ingress.annotations | nindent 4 }}
+    {{- tpl (toYaml .Values.ingress.annotations) . | nindent 4 }}
 spec:
   rules:
-    - host: {{ .Values.ingress.appOriginName }}
+    - host: {{ tpl .Values.ingress.appOriginName . }}
       http:
         paths:
           - path: /
@@ -17,7 +17,7 @@ spec:
                 name: {{ include "growthbook.fullname" . }}
                 port: 
                   number: {{ .Values.port.frontendPort }}
-    - host: {{ .Values.ingress.apiHostName }}
+    - host: {{ tpl .Values.ingress.apiHostName . }}
       http:
         paths:
           - path: /
@@ -29,7 +29,7 @@ spec:
                   number: {{ .Values.port.backendPort }}
   tls:
     - hosts:
-        - {{ .Values.ingress.appOriginName }}
-        - {{ .Values.ingress.apiHostName }}
+        - {{ tpl .Values.ingress.appOriginName . }}
+        - {{ tpl .Values.ingress.apiHostName . }}
       secretName: {{ .secretName }}
 {{- end -}}
\ No newline at end of file
```

What do you think, could we make these changes in the repo, so we allow users to define the ingress more dynamically?
