### ISSUE TITLE
unable to disable ui

### ISSUE THREAD

**Issue by usmaniqbal998** [one-acre-fund/oaf-public-charts#215]
I have following values.yaml file 

```
postgresql:
  enabled: false  # Disable in-cluster PostgreSQL
  host: "***"  
  postgresqlDatabase: "***"
  postgresqlUsername: "***"
  postgresqlPassword: "***"

general:
  serviceType: "LoadBalancer"  # Expose Apicurio via LoadBalancer (No Ingress)

ingress:
  enabled: false  # Explicitly disable Ingress

api:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

ui:
  enabled: false

ws:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

```

but after helm upgrade i always see ui pod created although ui is disabled in values yaml
